const Web3 = require('web3');

const url = 'https://BitFund:1234aaAA@apis.ankr.com/c48d86d29d2e4e619a65e0fd75ac2942/8d7dca9bc7ae0272d841c0c2f35f8ea9/eth/fast/ropsten'  // url string

const web3 = new Web3(new Web3.providers.HttpProvider("HTTP://127.0.0.1:7545"));

const abi = [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"cannotCreateMultiplePost","type":"error"},{"inputs":[],"name":"noPostForAddress","type":"error"},{"inputs":[{"internalType":"address","name":"reciever","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"donate","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"usr","type":"address"}],"name":"get","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"string","name":"title","type":"string"},{"internalType":"string","name":"content","type":"string"},{"internalType":"string","name":"photo_url","type":"string"},{"internalType":"address payable","name":"reciever","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"havePost","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"amount_needed","type":"uint256"},{"internalType":"string","name":"title","type":"string"},{"internalType":"string","name":"content","type":"string"},{"internalType":"string","name":"photo_url","type":"string"}],"name":"makePost","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"nPosts","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"posts","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"uint256","name":"amount_needed","type":"uint256"},{"internalType":"uint256","name":"amount_raised","type":"uint256"},{"internalType":"string","name":"title","type":"string"},{"internalType":"string","name":"content","type":"string"},{"internalType":"string","name":"photo_url","type":"string"},{"internalType":"address payable","name":"reciever","type":"address"}],"stateMutability":"view","type":"function"}]

const DonationContract = new web3.eth.Contract(abi, "0xe214107A334f9bAEde0889Cd3631d2ADA0803958")

export default DonationContract